### ISSUE TITLE
Ubuntu 16 Install error

### ISSUE THREAD

**Issue by scriptzteam** [Empornium/Luminance#1]
```
Database name: luminance
Database username: root
Database password: root
root@home:/var/www/html/Luminance# php application/entry.php setup install
Initializing legacy database table schemas
Initializing ORM database table schemas
Table clients: Adding column IPID
Caught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'Created'
#0 /var/www/html/Luminance/application/Services/DB.php(119): PDOStatement->execute(Array)
#1 /var/www/html/Luminance/application/Services/ORM.php(314): Luminance\Services\DB->raw_query('ALTER TABLE `cl...')
#2 /var/www/html/Luminance/application/Services/ORM.php(196): Luminance\Services\ORM->update_table(Array)
#3 /var/www/html/Luminance/application/Builtins/Setup/SetupPlugin.php(93): Luminance\Services\ORM->update_tables()
#4 [internal function]: Luminance\Builtins\Setup\SetupPlugin->install()
#5 /var/www/html/Luminance/application/Core/Controller.php(33): call_user_func_array(Array, Array)
#6 [internal function]: Luminance\Core\Controller->handle_path('install')
#7 /var/www/html/Luminance/application/Core/Master.php(264): call_user_func_array(Array, Array)
#8 [internal function]: Luminance\Core\Master->plugin('Setup', Array)
#9 /var/www/html/Luminance/application/Core/Master.php(250): call_user_func_array(Array, Array)
#10 /var/www/html/Luminance/application/Core/Master.php(146): Luminance\Core\Master->handle_request(Object(Luminance\Core\Request))
#11 /var/www/html/Luminance/application/entry.php(31): Luminance\Core\Master->run()
#12 {main}
--- ERROR during CLI execution ---
Corresponding HTTP response status: 500
Error message: Internal Server Error

```

**Comment by Empornium** [comment]
We assume you ran the configure step first, what MySQL version are you using?

Also, sorry for the delay in responding.

**Comment by Empornium** [comment]
After some investigation the cause is Ubuntu incorrectly configuring its default MySQL.

You will need to configure your database without the now deprecated 'NO_ZERO_DATE' and 'NO_ZERO_IN_DATE' options in order to install and use the software (and numerous other pieces of software as well).
