### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by panderuowo** [Empornium/Luminance#16]
Everything is working fine except a few things that I just wanted to point out.
When you try to save changes in a users profile the page returns an internal server error and logs show: 

2018/10/30 00:13:54 [error] 815#815: *11 FastCGI sent in stderr: "PHP message: Caught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'm.Email' in 'field list'
#0 /var/www/application/Services/DB.php(180): PDO->prepare('SELECT\n    m.Em...')
#1 /var/www/application/Services/OldDB.php(36): Luminance\Services\DB->legacy_query('SELECT\n    m.Em...')
#2 /var/www/application/Legacy/sections/user/takemoderate.php(135): Luminance\Services\OldDB->query('SELECT\n    m.Em...')
#3 /var/www/application/Legacy/sections/user/index.php(60): include('/var/www/applic...')
#4 /var/www/application/Core/LegacyHandler.php(41): require('/var/www/applic...')
#5 /var/www/application/Core/LegacyHandler.php(18): Luminance\Core\LegacyHandler->load_section('user')
#6 /var/www/application/Core/Master.php(306): Luminance\Core\LegacyHandler->handle_legacy_request('user')
#7 [internal function]: Luminance\Core\Master->legacy('user')
#8 /var/www/application/Core/Master.php(276): call_user_func_array(Array, Array)
#9 /var/www/application/Core/Master.php(161): Luminance\Core\Master->" while reading response header from upstream, client: censored, server: , request: "POST /user.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "censored.com", referrer: "https://censored.com/user.php?id=1"

and also when Radiance is in loop:
[2018-10-30 00:29:20] Query error: Field 'GroupID' doesn't have a default value in flush torrents with a qlength: 273 queue size: 2

**Comment by Empornium** [comment]
We're aware of this one, it's a remnant of a delete DB column. You could either remove the remaining references to the Email field or add the Email field to the users_main table. It's unused by the code but still referenced.

As for radiance, looks like the tracker is trying to save stats for a torrent that doesn't really exist, did you wipe your DB while the tracker was running?

**Comment by panderuowo** [comment]
Yeap I done that before and all is working fine.

As for Radiance I did not wipe the DB after uploading a torrent, checking the db table data I can see there is indeed a group ID of 1 associated with the torrent entry. 🤔 I'll just clean up everything and see if I can reproduce the issue again, could have been a hiccup.

**Comment by panderuowo** [comment]
Wiped everything and am still having the issue with group ID on new torrents, weird.
Edit: disabling strict mode did not resolve the issue and it seems that broke seeding unless my end is being strange. (Seeders / leechers show on the site, announce still OK but cannot download)
correction: disabling strict mode does remove the error just for me it has broken things.

**Comment by panderuowo** [comment]
hm now I am constantly getting: 1 failed announcements.

**Comment by panderuowo** [comment]
Seeds: | 0 of 1 connected | Peers: | 0 of 1 connected
Announce OK on host client
[Tracker status]
4 successful announcements
1 failed announcements

It can't be the seeder side as I am able to seed to anywhere else.

**Comment by Empornium** [comment]
Bit of a mystery. Which DB are you using (MySQL or MariaDB) and what version?

We run MariaDB 10.2 on our site and it all works fine with that, but the tracker code has run on various version of MySQL/MariaDB for years now.

**Comment by panderuowo** [comment]
I am using MySQL, I could try switching to MariaDB.

**Comment by Omniusol** [comment]
> 
> 
> I am using MySQL, I could try switching to MariaDB.

Why not take a look at https://github.com/HDInnovations/UNIT3D it may well suit you.

**Comment by panderuowo** [comment]
Sorry for the late update. mariadb fixes the issue with the query error but same issue still persists which is being unable to seed to anyone and announcements failing. When the event loop is started is radiance supposed to print open: x connections: x etc because for me starting event loop is printed then nothing at all

hm, is listen path required in radiance?

**Comment by Empornium** [comment]
listen_path is used for unix domain sockets, listen_host and listen_port are for network sockets. listen_path has some limitations and is really just for development purposes.

Printing starting event loop and nothing else is an indication that you have logging or daemon mode turned on, if it writes to logs then it won't write to console and for daemon mode it'll close all open file handles first.

If you want to view messages on the console in real time then use these settings:
```
daemonize           = false
syslog_path         = off
```

**Comment by panderuowo** [comment]
They're both left untouched from default but an older version of Radiance does print for me which is strange. With the loop supposedly running fine I still have an issue where a client cannot connect to a seeder, any ideas what could be causing this? All announcements seem fine until a client tries to download. I have some free time now so I'll actually look into my issues properly

**Comment by Empornium** [comment]
With syslog_level set to trace you should see an output like below:

```
[2018-11-01 16:09:52] Running in Foreground
[2018-11-01 16:09:52] Connecting to DB to load site options
[2018-11-01 16:09:52] MySQL connection grab called
[2018-11-01 16:09:52] MySQL connection issued: 0 (0)
[2018-11-01 16:09:52] MySQL connection create called
[2018-11-01 16:09:52] MySQL connection created: 0 (0)
[2018-11-01 16:09:52] Querying DB for EnableIPv6Tracker option
[2018-11-01 16:09:52] Querying DB for SitewideDoubleseedEndTime option
[2018-11-01 16:09:52] Querying DB for SitewideDoubleseedMode option
[2018-11-01 16:09:52] Querying DB for SitewideDoubleseedStartTime option
[2018-11-01 16:09:52] Querying DB for SitewideFreeleechEndTime option
[2018-11-01 16:09:52] Querying DB for SitewideFreeleechMode option
[2018-11-01 16:09:52] Querying DB for SitewideFreeleechStartTime option
[2018-11-01 16:09:52] MySQL connection release called
[2018-11-01 16:09:52] MySQL connection released: 1 (1)
[2018-11-01 16:09:52] MySQL connection release called
[2018-11-01 16:09:52] MySQL connection released: 1 (0)
[2018-11-01 16:09:52] Connecting to DB to load users
[2018-11-01 16:09:52] MySQL connection grab called
[2018-11-01 16:09:52] MySQL connection issued: 1 (0)
[2018-11-01 16:09:52] Loaded 20 users
[2018-11-01 16:09:52] MySQL connection release called
[2018-11-01 16:09:52] MySQL connection released: 1 (1)
[2018-11-01 16:09:52] MySQL connection release called
[2018-11-01 16:09:52] MySQL connection released: 1 (0)
[2018-11-01 16:09:52] Connecting to DB to load torrents
[2018-11-01 16:09:52] MySQL connection grab called
[2018-11-01 16:09:52] MySQL connection issued: 1 (0)
[2018-11-01 16:09:52] Loaded 20432 torrents
[2018-11-01 16:09:52] MySQL connection release called
[2018-11-01 16:09:52] MySQL connection released: 1 (1)
[2018-11-01 16:09:52] MySQL connection release called
[2018-11-01 16:09:52] MySQL connection released: 1 (0)
[2018-11-01 16:09:52] Connecting to DB to load tokens
[2018-11-01 16:09:52] MySQL connection grab called
[2018-11-01 16:09:52] MySQL connection issued: 1 (0)
[2018-11-01 16:09:52] Loaded 0 tokens
[2018-11-01 16:09:52] MySQL connection release called
[2018-11-01 16:09:52] MySQL connection released: 1 (1)
[2018-11-01 16:09:52] MySQL connection release called
[2018-11-01 16:09:52] MySQL connection released: 1 (0)
[2018-11-01 16:09:52] Connecting to DB to load blacklist
[2018-11-01 16:09:52] MySQL connection grab called
[2018-11-01 16:09:52] MySQL connection issued: 1 (0)
[2018-11-01 16:09:52] Loaded 2 clients into the blacklist
[2018-11-01 16:09:52] MySQL connection release called
[2018-11-01 16:09:52] MySQL connection released: 1 (1)
[2018-11-01 16:09:52] MySQL connection release called
[2018-11-01 16:09:52] MySQL connection released: 1 (0)
[2018-11-01 16:09:52] Listening with IPv4 INET socket.
[2018-11-01 16:09:52] Sockets up on port 34000, starting event loop!
[2018-11-01 16:09:53] 0 open, 0 connections (0/s), 0 requests (0/s)
```

The biggest change in this release is the DB connection pool. The only required change is modifying the user loading query to not reference the IP column in users_main.

**Comment by panderuowo** [comment]
[2018-11-01 23:36:08] [info]	Running in Foreground
[2018-11-01 23:36:08] [info]	Clearing peerlists and resetting peer counts...
[2018-11-01 23:36:08] [info]	done
[2018-11-01 23:36:08] [info]	Assuming no blacklist desired, disabling
[2018-11-01 23:36:08] [info]	Listening with IPv4 INET socket.
[2018-11-01 23:36:08] [info]	Sockets up on port 1111, starting event loop!

is what I get when I enable syslog_path /var/log/radiance/radiance.log

**Comment by Empornium** [comment]
A few things to try:

- Increase syslog_level to trace and see if there's anthing else going on.
- Try a build with --enable-debug as one of the configuration options.

**Comment by panderuowo** [comment]
[2018-11-02 00:34:19] [info]	Running in Foreground
[2018-11-02 00:34:19] [info]	Clearing peerlists and resetting peer counts...
[2018-11-02 00:34:19] [trace]	Connecting to DB to clear peer data
[2018-11-02 00:34:19] [trace]	MySQL connection grab called
[2018-11-02 00:34:19] [trace]	MySQL connection issued: 0 (0)
[2018-11-02 00:34:19] [trace]	MySQL connection create called
[2018-11-02 00:34:19] [trace]	MySQL connection created: 0 (0)
[2018-11-02 00:34:19] [trace]	MySQL connection release called
[2018-11-02 00:34:19] [trace]	MySQL connection released: 1 (1)
[2018-11-02 00:34:19] [trace]	MySQL connection release called
[2018-11-02 00:34:19] [trace]	MySQL connection released: 1 (0)
[2018-11-02 00:34:19] [info]	done
[2018-11-02 00:34:19] [trace]	Connecting to DB to load site options
[2018-11-02 00:34:19] [trace]	MySQL connection grab called
[2018-11-02 00:34:19] [trace]	MySQL connection issued: 1 (0)
[2018-11-02 00:34:19] [trace]	Querying DB for EnableIPv6Tracker option
[2018-11-02 00:34:19] [trace]	Querying DB for SitewideDoubleseedEndTime option
[2018-11-02 00:34:19] [trace]	Querying DB for SitewideDoubleseedMode option
[2018-11-02 00:34:19] [trace]	Querying DB for SitewideDoubleseedStartTime option
[2018-11-02 00:34:19] [trace]	Querying DB for SitewideFreeleechEndTime option
[2018-11-02 00:34:19] [trace]	Querying DB for SitewideFreeleechMode option
[2018-11-02 00:34:19] [trace]	Querying DB for SitewideFreeleechStartTime option
[2018-11-02 00:34:19] [trace]	MySQL connection release called
[2018-11-02 00:34:19] [trace]	MySQL connection released: 1 (1)
[2018-11-02 00:34:19] [trace]	MySQL connection release called
[2018-11-02 00:34:19] [trace]	MySQL connection released: 1 (0)
[2018-11-02 00:34:19] [trace]	Connecting to DB to load users
[2018-11-02 00:34:19] [trace]	MySQL connection grab called
[2018-11-02 00:34:19] [trace]	MySQL connection issued: 1 (0)
[2018-11-02 00:34:19] [trace]	Loaded 1 users
[2018-11-02 00:34:19] [trace]	MySQL connection release called
[2018-11-02 00:34:19] [trace]	MySQL connection released: 1 (1)
[2018-11-02 00:34:19] [trace]	MySQL connection release called
[2018-11-02 00:34:19] [trace]	MySQL connection released: 1 (0)
[2018-11-02 00:34:19] [trace]	Connecting to DB to load torrents
[2018-11-02 00:34:19] [trace]	MySQL connection grab called
[2018-11-02 00:34:19] [trace]	MySQL connection issued: 1 (0)
[2018-11-02 00:34:19] [trace]	Loaded 6 torrents
[2018-11-02 00:34:19] [trace]	MySQL connection release called
[2018-11-02 00:34:19] [trace]	MySQL connection released: 1 (1)
[2018-11-02 00:34:19] [trace]	MySQL connection release called
[2018-11-02 00:34:19] [trace]	MySQL connection released: 1 (0)
[2018-11-02 00:34:19] [trace]	Connecting to DB to load tokens
[2018-11-02 00:34:19] [trace]	MySQL connection grab called
[2018-11-02 00:34:19] [trace]	MySQL connection issued: 1 (0)
[2018-11-02 00:34:19] [trace]	Loaded 0 tokens
[2018-11-02 00:34:19] [trace]	MySQL connection release called
[2018-11-02 00:34:19] [trace]	MySQL connection released: 1 (1)
[2018-11-02 00:34:19] [trace]	MySQL connection release called
[2018-11-02 00:34:19] [trace]	MySQL connection released: 1 (0)
[2018-11-02 00:34:19] [trace]	Connecting to DB to load blacklist
[2018-11-02 00:34:19] [trace]	MySQL connection grab called
[2018-11-02 00:34:19] [trace]	MySQL connection issued: 1 (0)
[2018-11-02 00:34:19] [info]	Assuming no blacklist desired, disabling
[2018-11-02 00:34:19] [trace]	MySQL connection release called
[2018-11-02 00:34:19] [trace]	MySQL connection released: 1 (1)
[2018-11-02 00:34:19] [trace]	MySQL connection release called
[2018-11-02 00:34:19] [trace]	MySQL connection released: 1 (0)
[2018-11-02 00:34:19] [info]	Listening with IPv4 INET socket.
[2018-11-02 00:34:19] [info]	Sockets up on port 1111, starting event loop!
[2018-11-02 00:34:22] [debug]	0 open, 0 connections (0/s), 0 requests (0/s)
[2018-11-02 00:34:33] [trace]	Peer with IPv4 address censored added.
[2018-11-02 00:34:34] [trace]	Connecting to DB to flush peers
[2018-11-02 00:34:34] [trace]	MySQL connection grab called
[2018-11-02 00:34:34] [trace]	MySQL connection issued: 1 (0)
[2018-11-02 00:34:34] [trace]	Connecting to DB to flush torrents
[2018-11-02 00:34:34] [trace]	MySQL connection grab called
[2018-11-02 00:34:34] [trace]	MySQL connection issued: 1 (1)
[2018-11-02 00:34:34] [trace]	MySQL connection create called
[2018-11-02 00:34:34] [trace]	MySQL connection created: 1 (1)
[2018-11-02 00:34:34] [trace]	MySQL connection release called
[2018-11-02 00:34:34] [trace]	MySQL connection released: 2 (2)
[2018-11-02 00:34:34] [trace]	peers flushed in 1201 microseconds.
[2018-11-02 00:34:34] [trace]	MySQL connection release called
[2018-11-02 00:34:34] [trace]	MySQL connection released: 2 (1)
[2018-11-02 00:34:37] [trace]	Torrent flush queue size: 2, next query length: 273
[2018-11-02 00:34:37] [trace]	MySQL connection release called
[2018-11-02 00:34:37] [trace]	MySQL connection released: 2 (0)
[2018-11-02 00:34:37] [trace]	Connecting to DB to flush torrents
[2018-11-02 00:34:37] [trace]	MySQL connection grab called
[2018-11-02 00:34:37] [trace]	MySQL connection issued: 2 (0)
[2018-11-02 00:34:37] [trace]	MySQL connection release called
[2018-11-02 00:34:37] [trace]	MySQL connection released: 2 (1)
[2018-11-02 00:34:40] [trace]	Torrent flush queue size: 2, next query length: 273
[2018-11-02 00:34:40] [trace]	MySQL connection release called
[2018-11-02 00:34:40] [trace]	MySQL connection released: 2 (0)
[2018-11-02 00:34:40] [trace]	Connecting to DB to flush torrents
[2018-11-02 00:34:40] [trace]	MySQL connection grab called
[2018-11-02 00:34:40] [trace]	MySQL connection issued: 2 (0)
[2018-11-02 00:34:40] [trace]	MySQL connection release called
[2018-11-02 00:34:40] [trace]	MySQL connection released: 2 (1)
[2018-11-02 00:34:43] [trace]	Torrent flush queue size: 2, next query length: 273
[2018-11-02 00:34:43] [trace]	MySQL connection release called
[2018-11-02 00:34:43] [trace]	MySQL connection released: 2 (0)
[2018-11-02 00:34:43] [trace]	Connecting to DB to flush torrents
[2018-11-02 00:34:43] [trace]	MySQL connection grab called
[2018-11-02 00:34:43] [trace]	MySQL connection issued: 2 (0)
[2018-11-02 00:34:43] [trace]	MySQL connection release called
[2018-11-02 00:34:43] [trace]	MySQL connection released: 2 (1)
[2018-11-02 00:34:46] [trace]	Torrent flush queue size: 2, next query length: 273
[2018-11-02 00:34:46] [trace]	MySQL connection release called
[2018-11-02 00:34:46] [trace]	MySQL connection released: 2 (0)
[2018-11-02 00:34:46] [trace]	Connecting to DB to flush torrents
[2018-11-02 00:34:46] [trace]	MySQL connection grab called
[2018-11-02 00:34:46] [trace]	MySQL connection issued: 2 (0)
[2018-11-02 00:34:46] [trace]	MySQL connection release called
[2018-11-02 00:34:46] [trace]	MySQL connection released: 2 (1)
[2018-11-02 00:34:49] [trace]	Torrent flush queue size: 2, next query length: 273
[2018-11-02 00:34:49] [trace]	MySQL connection release called
[2018-11-02 00:34:49] [trace]	MySQL connection released: 2 (0)
[2018-11-02 00:34:49] [trace]	Connecting to DB to flush torrents
[2018-11-02 00:34:49] [trace]	MySQL connection grab called
[2018-11-02 00:34:49] [trace]	MySQL connection issued: 2 (0)
[2018-11-02 00:34:49] [trace]	MySQL connection release called
[2018-11-02 00:34:49] [trace]	MySQL connection released: 2 (1)
[2018-11-02 00:34:52] [trace]	Torrent flush queue size: 2, next query length: 273
[2018-11-02 00:34:52] [trace]	MySQL connection release called
[2018-11-02 00:34:52] [trace]	MySQL connection released: 2 (0)
[2018-11-02 00:34:52] [trace]	Connecting to DB to flush torrents
[2018-11-02 00:34:52] [trace]	MySQL connection grab called
[2018-11-02 00:34:52] [trace]	MySQL connection issued: 2 (0)
[2018-11-02 00:34:52] [trace]	MySQL connection release called
[2018-11-02 00:34:52] [trace]	MySQL connection released: 2 (1)

I do have 1 request 1 connection further down the log but a lot of repetitive filler

**Comment by Empornium** [comment]
Okay, this all looks normal.

So can you see anything in the log that matches up to your failed announce?

**Comment by panderuowo** [comment]
Nope, all looks the same. Is luminance compatible with any other trackers? Would be interesting to test.

**Comment by Empornium** [comment]
Nope, only Radiance.

Is the failed announce listed in your client or only in the tracker stats page?

**Comment by panderuowo** [comment]
Everything is fine in client. The failed announce is listed in tracker status amongst supposedly successful announcements and it is also tracking leech / seed fine. Very odd

**Comment by Empornium** [comment]
Hmmmm, might just be a counting error somehow?

I'll try to recreate it. At this point though, if the client is happy and the log shows nothing I'd kind of ignore it, as the tracker itself appears to be functioning.

**Comment by panderuowo** [comment]
I could ignore it if it were able to connect to seeders, in my case client cannot download from any seeders. 
Seeds: | 0 of 1 connected | Peers: | 0 of 1 connected, I'll just try to find the underlining issue.

**Comment by Empornium** [comment]
The tracker will never return your own seeds as in, if you have two clients announcing with the same passkey it will not connect them. I assume you've got two clients on two IPs with two different passkeys, right?

And hopefully one or both of them is connectable.

**Comment by panderuowo** [comment]
Issue resolved by changing keys. Sorry for the trouble.
