### ISSUE TITLE
HTTP Error 500 when uploading a torrent

### ISSUE THREAD

**Issue by ghost** [Empornium/Luminance#45]
Hi, I am experiencing an issue when trying to upload a torrent. All I get from the server is an HTTP Error 500. Here is the full trace from the logs:

```
2020/03/12 21:34:59 [error] 6#6: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Luminance\Legacy\curl_init() in /var/www/html/Luminance/application/Legacy/classes/Validate.php:511
Stack trace:
#0 /var/www/html/Luminance/application/Legacy/classes/Validate.php(333): Luminance\Legacy\Validate->get_presentation_size(Array)
#1 /var/www/html/Luminance/application/Legacy/sections/upload/upload_handle.php(222): Luminance\Legacy\Validate->ValidateForm(Array, Object(Luminance\Legacy\Text))
#2 /var/www/html/Luminance/application/Legacy/sections/upload/index.php(13): include('/var/www/html/L...')
#3 /var/www/html/Luminance/application/Core/LegacyHandler.php(41): require('/var/www/html/L...')
#4 /var/www/html/Luminance/application/Core/LegacyHandler.php(18): Luminance\Core\LegacyHandler->load_section('upload')
#5 /var/www/html/Luminance/application/Core/Master.php(306): Luminance\Core\LegacyHandler->handle_legacy_request('upload')
#6 [internal function]: Luminance\Core\Master->legacy('upload')
#7 /var/www/html/Luminance/ap" while reading response header from upstream, client:*, server: localhost, request: "POST /upload.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "*:9090", referrer: "http://*:9090/upload.php"
```

Any idea? Cheers!

**Comment by ghost** [comment]
I got it fixed by installing `php7.0-curl`. Maybe it could be added as a required php module in `INSTALL.md` in the future 👍
