### ISSUE TITLE
Database Install Error

### ISSUE THREAD

**Issue by drt420** [Empornium/Luminance#6]
Hello
I am receiving following error during database installation. Pls help in resolving same

> php application/entry.php setup install
Initializing legacy database table schemas
Initializing ORM database table schemas
Creating table options
Table clients: Adding column IPID
Caught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'Created'
#0 /var/www/nbtorrents.com/html/Luminance/application/Services/DB.php(128): PDOStatement->execute(Array)
#1 /var/www/nbtorrents.com/html/Luminance/application/Services/ORM.php(314): Luminance\Services\DB->raw_query('ALTER TABLE `cl...')
#2 /var/www/nbtorrents.com/html/Luminance/application/Services/ORM.php(196): Luminance\Services\ORM->update_table(Array)
#3 /var/www/nbtorrents.com/html/Luminance/application/Builtins/Setup/SetupPlugin.php(82): Luminance\Services\ORM->update_tables()
#4 [internal function]: Luminance\Builtins\Setup\SetupPlugin->install()
#5 /var/www/nbtorrents.com/html/Luminance/application/Core/Controller.php(33): call_user_func_array(Array, Array)
#6 [internal function]: Luminance\Core\Controller->handle_path('install')
#7 /var/www/nbtorrents.com/html/Luminance/application/Core/Master.php(267): call_user_func_array(Array, Array)
#8 [internal function]: Luminance\Core\Master->plugin('Setup', Array)
#9 /var/www/nbtorrents.com/html/Luminance/application/Core/Master.php(253): call_user_func_array(Array, Array)
#10 /var/www/nbtorrents.com/html/Luminance/application/Core/Master.php(147): Luminance\Core\Master->handle_request(Object(Luminance\Core\Request))
#11 /var/www/nbtorrents.com/html/Luminance/application/entry.php(31): Luminance\Core\Master->run()
#12 {main}
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'luminance.permissions' doesn't exist in /var/www/nbtorrents.com/html/Luminance/application/Services/DB.php:127
Stack trace:
#0 /var/www/nbtorrents.com/html/Luminance/application/Services/DB.php(127): PDO->prepare('SELECT ID FROM ...')
#1 /var/www/nbtorrents.com/html/Luminance/application/Repositories/PermissionRepository.php(40): Luminance\Services\DB->raw_query('SELECT ID FROM ...')
#2 /var/www/nbtorrents.com/html/Luminance/application/Services/Peon.php(87): Luminance\Repositories\PermissionRepository->getMinUserClassID()
#3 /var/www/nbtorrents.com/html/Luminance/application/Services/Peon.php(113): Luminance\Services\Peon->get_base_variables()
#4 /var/www/nbtorrents.com/html/Luminance/application/Core/Master.php(175): Luminance\Services\Peon->display('clierror.html', Array)
#5 /var/www/nbtorrents.com/html/Luminance/application/Core/Master.php(168): Luminance\Core\Master->process_response(Object(Luminance\Responses\Rendered))
#6 in /var/www/nbtorrents.com/html/Luminance/application/Services/DB.php on line 127

**Comment by drt420** [comment]
Solved, issue was with mysql strict mode
