### ISSUE TITLE
Invalid token format

### ISSUE THREAD

**Issue by blobb3r** [Empornium/Luminance#73]
Are we supposed to edit settings.ini before running php application/entry.php setup configure?

It hits me with a error:
```
PHP Fatal error:  Uncaught Luminance\Errors\InputError: Invalid token format in /var/www/application/Services/Crypto.php:266
Stack trace:
#0 /var/www/application/Services/Crypto.php(23): Luminance\Services\Crypto::hex2bin()
#1 /var/www/application/Core/Master.php(136): Luminance\Services\Crypto->__construct()
#2 /var/www/application/Core/Slave.php(39): Luminance\Core\Master->getService()
#3 /var/www/application/Core/Slave.php(34): Luminance\Core\Slave->prepareServices()
#4 /var/www/application/Core/Master.php(137): Luminance\Core\Slave->link()
#5 /var/www/application/Core/Slave.php(39): Luminance\Core\Master->getService()
#6 /var/www/application/Core/Slave.php(34): Luminance\Core\Slave->prepareServices()
#7 /var/www/application/Core/Master.php(137): Luminance\Core\Slave->link()
#8 /var/www/application/Core/Master.php(352): Luminance\Core\Master->getService()
#9 /var/www/application/Core/Master.php(87): Luminance\Core\Master->__get()
#10 /var/www/application/entry.php(32): Luminance\Core\Master->__construct()
#11 {main}
  thrown in /var/www/application/Services/Crypto.php on line 266
```

No changes after adding keys to the settings.ini. We need 32 char hex decimal keys right?

**Comment by blobb3r** [comment]
Fixed with example tokens: 

[keys]
enckey = 'AAAAAAAAAAAAAAAA'
crypto_key = '5AB1A81CDB8B279D62F3A3B405B51DBC'
rss_hash = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
