### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by drt420** [Empornium/Luminance#8]
Hello
I am getting following error in fedora php 7.1
Pls help in resolving same.

```
2018/02/07 15:40:17 [error] 30780#0: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /usr/share/nginx/nbtorrents.com/html/Lumina$
Stack trace:
#0 /usr/share/nginx/nbtorrents.com/html/Luminance/application/Services/Peon.php(503): Luminance\Services\Peon->get_scripts('')
#1 /usr/share/nginx/nbtorrents.com/html/Luminance/application/Services/Peon.php(140): Luminance\Services\Peon->get_header_vars(Array)
#2 /usr/share/nginx/nbtorrents.com/html/Luminance/application/Core/Master.php(182): Luminance\Services\Peon->display_page('@Authentication...', Array)
#3 /usr/share/nginx/nbtorrents.com/html/Luminance/application/Core/Master.php(154): Luminance\Core\Master->process_response(Object(Luminance\Responses\Rendered))
#4 /usr/share/nginx/nbtorrents.com/html/Luminance/application/entry.php(33): Luminance\Core\Master->run()
#5 {main}
  thrown in /usr/share/nginx/nbtorrents.com/html/Luminance/application/Services/Peon.php on line 185" while reading response header from upstream, client: 103.30.141.105, server: test.enjoythe.tv,$
```

**Comment by Empornium** [comment]
PHP 7.1 is not supported, 5.6 or 7.0
